export const userListActionType = {
    ADD_USERLIST: 'ADD_USERLIST',
    UPDATE_USERLIST: 'UPDATE_USERLIST',
    DELETE_USERLIST:'DELETE_USERLIST',
    FETCH_USERLIST:'FETCH_USERLIST'
};
export const postActionType = {
    ADD_POSTLIST: 'ADD_POSTLIST',
    UPDATE_POSTLIST: 'UPDATE_POSTLIST',
    DELETE_POSTLIST:'DELETE_POSTLIST',
    FETCH_POSTLIST:'FETCH_POSTLIST',
    FETCH_POSTDETAILS:'FETCH_POSTDETAILS',
    FETCH_COMMENTS:'FETCH_COMMENTS'
};